# Site settings
title: "'Cat'.concat('Man')"
email: your-email@domain.com
description: "'Cat'.concat('Man') is the official start-up got frisky with programming and had a djing baby blog of Reid Covington, the real CatMan."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
